#!/bin/bash
#
# runonce - Run maintenance scripts once
# Copyright (C) 2022 Eugenio "g7" Paolantonio <me@medesimo.eu>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the <organization> nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

source /usr/share/runonce/include.sh

enable_services() {
    local RUNONCE_QUEUED_STAMP_DIRECTORY="${1}"
    local RUNONCE_QUEUED_STAMP="${2}"
    local RUNONCE_CONTEXT="${3}"

    if [ -e "${RUNONCE_QUEUED_STAMP}" ]; then
        rm -f "${RUNONCE_QUEUED_STAMP}"

        for queued in "$(ls ${RUNONCE_QUEUED_STAMP_DIRECTORY}/*)"; do
            script_name="$(basename ${queued})"

            [ -e "${RUNONCE_TARGETS}/${script_name}" ] && target=$(basename $(cat "${RUNONCE_TARGETS}/${script_name}" | head -n 1))

            [ -n "${target}" ] || target="default.target"

            target=${target#*:}

            mkdir -p "/run/systemd/${RUNONCE_CONTEXT}/${target}.wants"
            ln -s "/usr/lib/systemd/${RUNONCE_CONTEXT}/runonce@.service" "/run/systemd/${RUNONCE_CONTEXT}/${target}.wants/runonce@${script_name}.service"
        done
    fi
}

enable_services ${RUNONCE_QUEUED_STAMP_DIRECTORY} ${RUNONCE_QUEUED_STAMP} system

for user in $(get_homedirs); do
	set_user_directories $user
	enable_services ${RUNONCE_QUEUED_STAMP_DIRECTORY} ${RUNONCE_QUEUED_STAMP} user
done

exit 0
